### ISSUE TITLE
Feature Request: Upload all existing assets and replace with cloudinary links

### ISSUE THREAD

**Issue by lovettbarron** [jordanhandy/obsidian-cloudinary-uploader#16]
Request: In Settings or via the command palette, trigger a bulk upload of all locally referenced assets to cloudinary via the user's settings. Action should probably include a prompt to backup.

Use case: Creating a new vault from existing md docs and assets. Specifically vault via obsidian-garden (or in my case, a custom solution).

Really appreciate the plugin, and I think this would be a dramatic improvement.

**Comment by jordanhandy** [comment]
@lovettbarron Thank you for taking the time to use the plugin -- I really appreciate it.
I'll take a look into this

**Comment by jordanhandy** [comment]
Released as [1.0.0](https://github.com/jordanhandy/obsidian-cloudinary-uploader/releases/tag/1.0.0)
