### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by menagerie198** [jordanhandy/obsidian-cloudinary-uploader#19]
Hi Jordan
The most recent update is failing for me. Obsidian says nothing more than 'failed to install plugin: Cloudinary uploader'.

**Comment by jordanhandy** [comment]
Interesting, I've never experienced that before with my plugin. What version are you currently on?

Can you create a new vault as a test and install the plugin from scratch?

I suppose you could do it from your main vault, though I wouldn't want you to uninstall it and not be able to get it back.

Also, if you're able to look at the developer console, I'd be interested to see if there are any logs when that error occurs

**Comment by menagerie198** [comment]
Sorry Jordan, I have been away from my pooter for a bit. I deleted the plugin (v1.0.0), and now I have no Cloudinary Uploader'. That is a bit of a problem for me. I keep getting the 'failed to install' message. The Dev Console gives me an error message that I understand not at all. Here it is…
![2024-06-14 (1)](https://github.com/jordanhandy/obsidian-cloudinary-uploader/assets/7330436/65c3821f-a33e-4e8a-bcbf-73e110cb3c5d)

**Comment by menagerie198** [comment]
I managed to install v1.0.0 and got it working, but the update continues to fail. I also created a new empty vault, and the update failed in that too. Here is what the Dev Console shows after that… 
![image](https://github.com/jordanhandy/obsidian-cloudinary-uploader/assets/7330436/ed989931-13a8-4cc8-894c-71187845f659)

**Comment by jordanhandy** [comment]
Hi @menagerie198 
Can you try an update / install again?

I updated the release.  Obsidian should pick it up.  Let me know if the install works.

**Comment by menagerie198** [comment]
Successfully installed v1.0.2! Thanks mate

**Comment by jordanhandy** [comment]
Glad it worked for you. Apologies for the inconvenience
