### ISSUE TITLE
Upload failing

### ISSUE THREAD

**Issue by menagerie198** [jordanhandy/obsidian-cloudinary-uploader#21]
Hi Jordan, sorry to be a pain. Using v1.0.2 I am consistently getting a failed upload on pasting an image into Obsidian. I just get `![uploading...](3jt.nv41)` in Source mode, and `3jt.nv42 could not be found` in Live Preview.
I tried rolling back to 1.0.0, and 0.03 - same result. So it looks like there is something wrong my end.
This is what the Dev Console offers… Can you help?
![image](https://github.com/jordanhandy/obsidian-cloudinary-uploader/assets/7330436/b1355a53-19f1-4d73-8322-68f1144541fb)

**Comment by jordanhandy** [comment]
Can you send me a screenshot of your plugin settings? You've defined your cloud name and upload preset name, correct?

Is this a drag / drop, or a ctrl / cmd + c, ctrl / cmd + v that you're using to trigger the paste?

**Comment by menagerie198** [comment]
Here you go…. Cloudname and upload template defined. I have used Right Click>copy image, from a webpage, then Ctrl+V 
![2024-06-17 (2)](https://github.com/jordanhandy/obsidian-cloudinary-uploader/assets/7330436/35e423e5-5f8d-415c-85ea-d6e33f29fe5c)
![2024-06-17 (1)](https://github.com/jordanhandy/obsidian-cloudinary-uploader/assets/7330436/a24ae7f6-9c21-4eda-bf95-df038e802cf6)
![2024-06-17](https://github.com/jordanhandy/obsidian-cloudinary-uploader/assets/7330436/41c7b7b9-b043-424d-aac8-3059f63e0327)

**Comment by jordanhandy** [comment]
@menagerie198 
Settings seem fine to me.

What version of Obsidian are you running?  What about web browser that you copied the media from?  Seems like your system doesn't have access to `FormData` which is what builds your request to upload to Cloudinary, though it is part of the Node API. since v18 and should be available.

Can you try updating the Obsidian app if you're not on the current version?

**Comment by menagerie198** [comment]
Ah … possibly it is the Obsidian version I am using. It is an Alpha, with the latest Electron version. I will try to figure out how to roll back to the previous version. Might take me a little while - its getting close to sleepy time here.

**Comment by menagerie198** [comment]
Yup -- that was it! I rolled back to the public Obsidian 1.6.3, with Electron version ?? and all is well again with Cloudinary/Uploader. 
It seems there is something in Electron 30 that doesn’t get on with Cloudinary, and/or your plugin.

**Comment by jordanhandy** [comment]
Noted.  Thanks for the info.
Maybe I'll look at seeing if I can fix that up

**Comment by menagerie198** [comment]
Just to note that with the latest version of Obsidian (v 1.6.5, including the latest installer) all is well. Cloudinary Uploader works as intended.

**Comment by jordanhandy** [comment]
Thanks for confirming.  I'll close this for now.
From what I could find, it looks like this was a bug with the version of Electron that was in the alpha. (https://github.com/electron/electron/issues/42381) 

Since Obsidian uses the newest version, the fix to the above issue has been applied.
