### ISSUE TITLE
为什么我图片上传成功了，图片上面还会多出一行没用的提示

### ISSUE THREAD

**Issue by fqjedu** [jordanhandy/obsidian-cloudinary-uploader#3]
![image](https://user-images.githubusercontent.com/86455835/221446957-6888a0a7-ab6b-4bc8-b91c-bb2ba0b6e5a2.png)

**Comment by fqjedu** [comment]
解决了，之前使用 picgo + image auto upload plugin 来实现图床的，如果用 emo 插件的话，把之前那套方案关掉就行了

**Comment by fqjedu** [comment]
错误信息是我把 picgo 关掉了，然后导致上传图片失败，由 image auto upload plugin 产生的

**Comment by jordanhandy** [comment]
Closing
This plugin is not related to Picgo
