### ISSUE TITLE
Add f_auto option to URL

### ISSUE THREAD

**Issue by charlesroper** [jordanhandy/obsidian-cloudinary-uploader#4]
Firstly, thanks for this plugin - it's *so* handy.

I've got a feature request. I find that for every image I add to Obsidian/Cloudinary, I end up adding `f_auto` to the URL. More often than not, this results in an avif as a response, which is great. So my request is: would it be possible to either specify, or default to, `f_auto` mode?

More about f_auto here: https://cloudinary.com/documentation/video_optimization#automatic_format_selection_f_auto

Many thanks.

**Comment by jordanhandy** [comment]
Hi @charlesroper, thanks for the feedback. Much appreciated.

Regarding the request, I'll take a look into this over the weekend and maybe take a crack at it.

No ETA currently

**Comment by charlesroper** [comment]
Great, thanks!

**Comment by jordanhandy** [comment]
> Great, thanks!

Hi @charlesroper, 
Latest build should have this toggle for you.

From reading the link you sent, it's a URL edit only?  Let me know if this is what you were looking for

**Comment by charlesroper** [comment]
Just updated. It works perfectly, thank you!

Yes, it's just a URL edit. Cloudinary smartly delivers other formats if the browser supports them and the size is smaller than the original. You can tell it's working by opening devtools Network tab and looking at the image format response. It'll usually respond with an AVIF in Obsidian (on Windows at least - not tried other platforms)

E.g. this PNG screenshot downloads for me as an AVIF:

![](https://res.cloudinary.com/charlesr/image/upload/f_auto/v1681298427/obsidian/ddhbmnwznmtmsimj7oxv.png)

It's showing a JPG that has downloaded as an AVIF in the Network panel in Obsidian.

(if a PNG is already tightly optimised, it'll still return the original PNG)

**Comment by jordanhandy** [comment]
Thanks for the info. Very interesting.
Glad it's working for you.
