### ISSUE TITLE
Pasting file to obsidian note just add it's as normal image file inside vault, it's not uploaded to cloudinary

### ISSUE THREAD

**Issue by mwoz123** [jordanhandy/obsidian-cloudinary-uploader#9]
I can't make it  work :( 
Pasting file to obsidian note just add it's as normal image file inside vault, it's not uploaded to cloudinary nor link is replaced with link to image :(

## note, after pasting image (in "source view") :
![image](https://github.com/jordanhandy/obsidian-cloudinary-uploader/assets/4487025/6ba9d574-0a3a-49c6-88d5-4dd638dc8f7b)

## after pasting image is added to local vault:
![image](https://github.com/jordanhandy/obsidian-cloudinary-uploader/assets/4487025/a0ea9da5-825a-4e28-a723-8c847a59f0c5)

## My cloudinary account: 
![image](https://github.com/jordanhandy/obsidian-cloudinary-uploader/assets/4487025/ea48b26f-2085-4b78-ad87-71fea72fa5e1)

### my configuration:
![image](https://github.com/jordanhandy/obsidian-cloudinary-uploader/assets/4487025/24d7c5ab-ca0b-440d-9c7e-ee9f6da217d1)

### Upload Preset :
![image](https://github.com/jordanhandy/obsidian-cloudinary-uploader/assets/4487025/c2284332-4a5f-45fc-81f2-473b92e92bf6)

# details:
Obsidian version 1.3.5 
[obsidian-cloudinary-uploader](https://github.com/jordanhandy/obsidian-cloudinary-uploader) version 1.1.0

**Comment by gyunseo** [comment]
You must set the `Cloud Upload Template` field value.

> When the preset is created, it will have a "name" associated with it. Use this name in the "Upload Preset" field in Obisidan

[READ this document](https://jordanhandy.github.io/obsidian-cloudinary-uploader/configuring-cloudinary/)
